/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'clothing' : IDL.Null,
  'miscellaneous' : IDL.Null,
  'food' : IDL.Null,
  'furniture' : IDL.Null,
  'stationery' : IDL.Null,
  'books' : IDL.Null,
  'electronics' : IDL.Null,
});
export const ListingType = IDL.Variant({
  'trade' : IDL.Null,
  'free' : IDL.Null,
  'sale' : IDL.Null,
});
export const Condition = IDL.Variant({
  'new' : IDL.Null,
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'poor' : IDL.Null,
  'likeNew' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'contact' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'hostel' : IDL.Text,
});
export const ListingStatus = IDL.Variant({
  'active' : IDL.Null,
  'fulfilled' : IDL.Null,
  'traded' : IDL.Null,
  'sold' : IDL.Null,
});
export const ItemListing = IDL.Record({
  'id' : IDL.Text,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'desc' : IDL.Text,
  'createdAt' : Time,
  'seller' : IDL.Principal,
  'listingType' : ListingType,
  'category' : Category,
  'price' : IDL.Opt(IDL.Nat),
  'photos' : IDL.Vec(ExternalBlob),
  'condition' : Condition,
});
export const RequestStatus = IDL.Variant({
  'fulfilled' : IDL.Null,
  'open' : IDL.Null,
});
export const WantedRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'title' : IDL.Text,
  'requester' : IDL.Principal,
  'desc' : IDL.Text,
  'createdAt' : Time,
  'category' : Category,
  'budget' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        Category,
        ListingType,
        Condition,
        IDL.Vec(ExternalBlob),
      ],
      [IDL.Text],
      [],
    ),
  'createRequest' : IDL.Func(
      [IDL.Text, IDL.Text, Category, IDL.Opt(IDL.Nat)],
      [IDL.Text],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Text], [], []),
  'deleteRequest' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([IDL.Text], [ItemListing], ['query']),
  'getListingsBySeller' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ItemListing)],
      ['query'],
    ),
  'getRequest' : IDL.Func([IDL.Text], [WantedRequest], ['query']),
  'getRequestsByRequester' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WantedRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markListingStatus' : IDL.Func([IDL.Text, ListingStatus], [], []),
  'markRequestFulfilled' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateListingPhotos' : IDL.Func([IDL.Text, IDL.Vec(ExternalBlob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'clothing' : IDL.Null,
    'miscellaneous' : IDL.Null,
    'food' : IDL.Null,
    'furniture' : IDL.Null,
    'stationery' : IDL.Null,
    'books' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const ListingType = IDL.Variant({
    'trade' : IDL.Null,
    'free' : IDL.Null,
    'sale' : IDL.Null,
  });
  const Condition = IDL.Variant({
    'new' : IDL.Null,
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'poor' : IDL.Null,
    'likeNew' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'contact' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'hostel' : IDL.Text,
  });
  const ListingStatus = IDL.Variant({
    'active' : IDL.Null,
    'fulfilled' : IDL.Null,
    'traded' : IDL.Null,
    'sold' : IDL.Null,
  });
  const ItemListing = IDL.Record({
    'id' : IDL.Text,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'desc' : IDL.Text,
    'createdAt' : Time,
    'seller' : IDL.Principal,
    'listingType' : ListingType,
    'category' : Category,
    'price' : IDL.Opt(IDL.Nat),
    'photos' : IDL.Vec(ExternalBlob),
    'condition' : Condition,
  });
  const RequestStatus = IDL.Variant({
    'fulfilled' : IDL.Null,
    'open' : IDL.Null,
  });
  const WantedRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'title' : IDL.Text,
    'requester' : IDL.Principal,
    'desc' : IDL.Text,
    'createdAt' : Time,
    'category' : Category,
    'budget' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          Category,
          ListingType,
          Condition,
          IDL.Vec(ExternalBlob),
        ],
        [IDL.Text],
        [],
      ),
    'createRequest' : IDL.Func(
        [IDL.Text, IDL.Text, Category, IDL.Opt(IDL.Nat)],
        [IDL.Text],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Text], [], []),
    'deleteRequest' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([IDL.Text], [ItemListing], ['query']),
    'getListingsBySeller' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ItemListing)],
        ['query'],
      ),
    'getRequest' : IDL.Func([IDL.Text], [WantedRequest], ['query']),
    'getRequestsByRequester' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WantedRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markListingStatus' : IDL.Func([IDL.Text, ListingStatus], [], []),
    'markRequestFulfilled' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateListingPhotos' : IDL.Func([IDL.Text, IDL.Vec(ExternalBlob)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };