/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'clothing' : null } |
  { 'miscellaneous' : null } |
  { 'food' : null } |
  { 'furniture' : null } |
  { 'stationery' : null } |
  { 'books' : null } |
  { 'electronics' : null };
export type Condition = { 'new' : null } |
  { 'fair' : null } |
  { 'good' : null } |
  { 'poor' : null } |
  { 'likeNew' : null };
export type ExternalBlob = Uint8Array;
export interface ItemListing {
  'id' : string,
  'status' : ListingStatus,
  'title' : string,
  'desc' : string,
  'createdAt' : Time,
  'seller' : Principal,
  'listingType' : ListingType,
  'category' : Category,
  'price' : [] | [bigint],
  'photos' : Array<ExternalBlob>,
  'condition' : Condition,
}
export type ListingStatus = { 'active' : null } |
  { 'fulfilled' : null } |
  { 'traded' : null } |
  { 'sold' : null };
export type ListingType = { 'trade' : null } |
  { 'free' : null } |
  { 'sale' : null };
export type RequestStatus = { 'fulfilled' : null } |
  { 'open' : null };
export type Time = bigint;
export interface UserProfile {
  'id' : Principal,
  'contact' : string,
  'displayName' : string,
  'createdAt' : Time,
  'hostel' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WantedRequest {
  'id' : string,
  'status' : RequestStatus,
  'title' : string,
  'requester' : Principal,
  'desc' : string,
  'createdAt' : Time,
  'category' : Category,
  'budget' : [] | [bigint],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<
    [
      string,
      string,
      [] | [bigint],
      Category,
      ListingType,
      Condition,
      Array<ExternalBlob>,
    ],
    string
  >,
  'createRequest' : ActorMethod<
    [string, string, Category, [] | [bigint]],
    string
  >,
  'deleteListing' : ActorMethod<[string], undefined>,
  'deleteRequest' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[string], ItemListing>,
  'getListingsBySeller' : ActorMethod<[Principal], Array<ItemListing>>,
  'getRequest' : ActorMethod<[string], WantedRequest>,
  'getRequestsByRequester' : ActorMethod<[Principal], Array<WantedRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markListingStatus' : ActorMethod<[string, ListingStatus], undefined>,
  'markRequestFulfilled' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateListingPhotos' : ActorMethod<[string, Array<ExternalBlob>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];